### ISSUE TITLE
data from bulk RNA-seq

### ISSUE THREAD

**Issue by johaGL** [msraredon/Connectome#5]
Hello,  thank you for your fantastic toolkit . We would like to implement *Connectome* , but in your paper the usage seems to be restricted to Single Cell omics experiments. In our case, we have performed *bulk RNA-seq* different time-points across six cell types  (samples  trustworthy classified). We would appreciate any indications/comments from your team, i.e.   if we  yield a dataframe  containing cell-type samples and their respective strongly expressed/relevant protein-coding genes, would it be suitable for Connectome analysis?? if not, Would  raw-count matrix (dim 22000 protein-coding genes x 52 [6 celltypeSamples x 4 time-points x 3(2) replicates], work to produce the connectome ?

**Comment by msraredon** [comment]
Hi! Interesting question.  The scripts are not really made for this, so I think it would require some significant re-working of the codes, but this is in principle doable and your data seems crafted in a way to make such an analysis appropriate.

If you make one dataframe for each timepoint, with rows being genes and columns being celltype, it can take the place of the object currently made by line 100 in `CreateConnectome.` You will have to scale this by row then to make a substitute for the object made in line 101. Line 102 cannot be calculated from your information, so you'll have to either edit downstream functions to accomodate or put in dummy data (make every percentage expressed equal to 1, for instance.

There will certainly be some bugs, since the software is expecting certain pieces of information and structure that is simply not accessible in your application. Off the top of my head, you will have trouble anytime a percentage expresses is expected, and you would not be able to calculate p-values using Wilcoxon rank, so you'd have to make that argument = F.

My overall recommendation would be to either a) start from scratch using `CreateConnectome` as a guide, or b) to copy the script from CreateConnectome and edit it so that it can run on your data and provide a reasonable output.  Then, depending on what column names you have in the resulting object, editing downstream functions as well so they can handle you datastructure. Alternatively, you can add dummy columns with the right labels so that downstream functions can run.

Hope this helps.

S

**Comment by johaGL** [comment]
Thank you very much, your answer help us a lot. We'll discuss this with the rest of my team.
