### ISSUE TITLE
Cut off for FilterConnectome

### ISSUE THREAD

**Issue by sneddonucsf** [msraredon/Connectome#6]
Hello, 

Thank you for the great package! I had a question regarding the filtering for the Connectome. I have been following the vignette and am a little confused on how to choose the cut offs based on these plots: 

````
p1 <- ggplot(connectome, aes(x=ligand.scale)) + geom_density() + ggtitle('Ligand.scale')
p2 <- ggplot(connectome, aes(x=recept.scale)) + geom_density() + ggtitle('Recept.scale')
p3 <- ggplot(connectome, aes(x=percent.target)) + geom_density() + ggtitle('Percent.target')
p4 <- ggplot(connectome, aes(x=percent.source)) + geom_density() + ggtitle('Percent.source')
plot_grid(p1,p2,p3,p4)
```` 

Is it that all of the "connections" are relevant and that, for the vignette, you just wanted to focus on a few? 

Thanks!

**Comment by msraredon** [comment]
Great question. Sorry if this isn't clear in the vignette. The appropriate cutoff depends on the scientific question you're asking and what is of interest to you to focus on:

1. Pecent.target/source -- I generally use a cutoff of 10-20%, since anything below this is in such a tiny fraction of the cells within a given cluster that it doesn't seem "real" when you go back and look at the raw data. However, note that certain high-yield molecules, like Wnts and Notch signals, are often only captured in ~5% of clusters, even though they tend to be highly celltype specific.
2. Scaled values -- these are an indicator of celltype/cluster specificity. A higher number is a higher z-score within the total system, meaning that the expression level is that number of standard deviations above or below the mean value in the entire single cell dataset. High values will be genes which are preferentially expressed by a specific cluster, far above the mean value for the system. In general our lab considers signals fitting this pattern to be highly biologically relevant.
3. You can also cutoff based on the normalized values, to capture the "strong" signals even if they aren't cell-type specific, though that has proven far less useful in our hands for most biological questions

Re: the plots you mention above, they are provided to allow visualization of the distributions. The long right-hand "tail" in the plot, particularly in the scaled values plot, is the really good stuff / highly specific edges / stuff you want to keep. In the vignettes, I would set the threshold at no lower than 0.25 for both ligand and receptor to cut out the vast majority of low-yield "noise" edges. You could set it as high as 1 or 2 though if you want to only look at really specific, really statistically significant edges.

Of note, if you run the p-values in the original connectome function, you can also filter on this, which people tend to like because they are p-values. Correlates very well with the scaled values however, and calculating p-values takes a good deal longer computation time. Either works well though to identify edges which preferentially associate with a given cell type.

Hope this helps. Let me know if more questions or if not useful.

S
