### ISSUE TITLE
Error: Since you set ``grid.col``, the length should be either 1 or number of sectors, or set your ``grid.col`` as vector with names.

### ISSUE THREAD

**Issue by sailseem** [msraredon/Connectome#8]
Dear developer,
    Thank you for developing such a great package. I got one problem when I perform the CircosPlot.
Here is my codes:
grid.col <- as.vector(c("#006469","#00C6C9","#FFB637"))
names(grid.col) <- c('macrophage','microglia','ECs')
CircosPlot(low.con2,sources.include =c('macrophage','microglia'),
           targets.include = c('ECs'),lab.cex = 0.6,min.pct = 0.25,min.z=1,cols.use=grid.col)
this is my error:

**Error: Since you set ``grid.col``, the length should be either 1 or number of sectors, or set your
``grid.col`` as vector with names.
In addition: Warning message:
Since you have set `order`, you should better set `grid.col` as a named vector where sector
names are the vector names, or else the color will be wrongly assigned.** 

but when I increase the min.pct=0.5, which the plot can be shown successfully.  I don't know why, maybe replicates of ligand-receptor pairs? can you help me with it?

**Comment by msraredon** [comment]
CircosPlot can only handle genes being either a ligand or a receptor., but not both at the same time. This may the the issue, if this is being used with a custom ground truth that has a single genes categorized as both. If you remove this from the ground truth, this should work fine. I think that the percentage cutoff you're adding is removing these duplications, which is why it plots with a higher threshold. Let me know if this fix doesn't work.

S

**Comment by sailseem** [comment]
Thanks for your reply. I can plot out successfully now.
but when I compare within two groups, I encounter another problem.

diff <- DifferentialConnectome(ifnb.con.list[[1]],ifnb.con.list[[2]])
**Error in DifferentialConnectome(ifnb.con.list[[1]], ifnb.con.list[[2]]) : 
  
Connectomes do not have identical edges.
In addition: Warning message:
In base1$edge != base2$edge :
  longer object length is not a multiple of shorter object length**


can you help me with this one, thank you very much~

**Comment by msraredon** [comment]
This error is the result of trying to run `DifferentialConnectome` on two connectomes which do not have identical edges (where edges here refers to specific sendingcelltype - ligand - receptor - receivingcelltype combinations). This can occur if the same ligands and receptors are not present in both datasets, or if the same celltypes are not present in both datasets, or if the two connectomes have been filtered _before_ running `DifferentialConnectome` (since a common filtration threshold will likely have different effects on which edges remain in one connectome versus another.)

This issue can be investigated by 1) checking that the same ligands, receptors, and celltypes are present in the two original Seurat objects and then 2) making sure to not filter the connectomes prior to running `DifferentialConnectome`. It should work at that point. If it doesn't, please let me know.

S

**Comment by sailseem** [comment]
all right, i see your point. Thanks again.Really appreciated!!!
